<Project ToolsVersion="Current" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <OutputType>Exe</OutputType>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <AssemblyName>RuleChecks</AssemblyName>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" /><Reference Include="System.Core" />
    <Compile Include="Program.cs" />
    <ProjectReference Include="..\..\BarangayDocumentSystem\BarangayDocumentSystem.csproj">
      <Project>{9077BDF9-C14F-4BC1-A068-2BF52A9FA8CB}</Project>
      <Name>BarangayDocumentSystem</Name>
    </ProjectReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
